docs: add user and dev guides for rocm-docs-core
RadeonOpenCompute/rocm-docs-core pull request #281
Opened 2023-07-04 22:47 UTC by samjwu

closes https://github.com/RadeonOpenCompute/rocm-docs-core/issues/226

add linting guides, explanations, etc.

2023-07-05 11:47 UTC, Maetveis requested changes
One doc needs to be moved, but otherwise, this is good start for these pages.

2023-07-05 11:47 UTC, Maetveis commented on docs/.sphinx/_toc.yml.in
> +      - file: developer_guide/doxygen_integration
This should be in the user guide. The user guide is for **users** of `rocm-docs-core` (i.e. developers working on the documentation of other projects that make use of `rocm-docs-core`), while the developer guide is for developers of `rocm-docs-core` itself.

2023-07-05 15:07 UTC, samjwu commented on docs/.sphinx/_toc.yml.in
> +      - file: developer_guide/doxygen_integration
Makes sense. Moved in [ce78ae7 docs: move doxygen integration guide from developer to user guides](https://github.com/RadeonOpenCompute/rocm-docs-core/pull/281/commits/ce78ae7c59c19a5debb1d5053a28ea63c1be3999)

2023-07-06 06:06 UTC, Maetveis approved these changes

2023-07-06 14:40 UTC, merged