API reference styling
RadeonOpenCompute/rocm-docs-core pull request #36
Opened 2023-03-27 07:29 UTC by Maetveis

Style the doxysphinx generated pages using [doxygen-awesome-css](https://github.com/jothepro/doxygen-awesome-css)
modified by integrating into the sphinx-book-theme's dark/light themes.

The doxygen header/footer and the the stylesheets are copied in with rocm-docs-core, projects need to set the path to them in their Doxyfile to use these themes.

This also removes the need for sass (and node.js) to be installed as the stylesheets are installed in their already processed form.

Stacked upon #32, it should be merged first.

2023-03-27 23:39 UTC, samjwu requested changes

2023-03-27 23:39 UTC, samjwu commented on docs/demo/doxygen/Doxyfile
> +HTML_HEADER            = ../../_doxygen/header.html
```suggestion
HTML_HEADER            = ../../../src/rocm_docs/data/_doxygen/header.html
```

2023-03-27 23:39 UTC, samjwu commented on docs/demo/doxygen/Doxyfile
> +HTML_FOOTER            = ../../_doxygen/footer.html
```suggestion
HTML_FOOTER            = ../../../src/rocm_docs/data/_doxygen/footer.html
```

2023-03-27 23:39 UTC, samjwu commented on docs/demo/doxygen/Doxyfile
> +HTML_STYLESHEET        = ../../_doxygen/stylesheet.css
```suggestion
HTML_STYLESHEET        = ../../../src/rocm_docs/data/_doxygen/stylesheet.css
```

2023-03-27 23:39 UTC, samjwu commented on docs/demo/doxygen/Doxyfile
> +HTML_EXTRA_STYLESHEET  = ../../_doxygen/extra_stylesheet.css
```suggestion
HTML_EXTRA_STYLESHEET  = ../../../src/rocm_docs/data/_doxygen/extra_stylesheet.css
```

2023-03-27 23:46 UTC, samjwu commented
Doxyfile looks good, but I noticed some things. We may want to add graphviz as a requirement to run dot as it's mentioned in the Doxyfile

2023-03-28 07:46 UTC, Maetveis commented on docs/demo/doxygen/Doxyfile
> +HTML_HEADER            = ../../_doxygen/header.html
`rocm-docs-core` copies these files to a `_doxygen` subfolder in the same folder that the sphinx `conf.py` is in, so this works as is, and it is the same as how dependent projects would have it in _their_ doxyfiles. I would prefer it stay this way, rather than consume from the package sources directly.

2023-03-28 07:49 UTC, Maetveis commented
> Doxyfile looks good, but I noticed some things. 

Responded inline

> We may want to add graphviz as a requirement to run dot as it's mentioned in the Doxyfile

If we enable readthedocs for this repo, then we'd need to add graphviz to it, but note that the Doxyfile is not installed in consuming projects, they can each choose whether to use dot.

2023-03-28 13:15 UTC, saadrahim commented
In the interest of time, merging this. @samjwu any further concerns please make it as issue.

2023-03-28 13:15 UTC, saadrahim approved these changes

2023-03-28 13:16 UTC, merged